- id: clang-format
  name: clang-format
  description: Run `clang-format` on C++ files
  args: [-style=Google]
  language: system
  types: [c++]
  entry: clang-format -i

- id: cpplint
  name: cpplint
  description: Run `cpplint` on C++ files
  language: python
  types: [c++]
  entry: cpplint

- id: cmake-format
  name: cmake-format
  description: Run cmake-format on cmake files
  args: [--in-place]
  language: python
  types: [cmake]
  entry: cmake-format

- id: cmake-lint
  name: cmake-lint
  description: Run cmake-lint on cmake files
  language: python
  types: [cmake]
  entry: cmake-lint